#!/bin/bash

echo "🔧 Test du chat frontend"
echo "======================="

echo "📋 Instructions de test pour le frontend..."

echo ""
echo "1️⃣ Démarrer le frontend:"
echo "   cd frontend/Rosa && npm run dev"
echo "   Ouvrir http://localhost:5175"

echo ""
echo "2️⃣ Test avec 5 joueurs:"
echo "   - Ouvrir 5 onglets: http://localhost:5175"
echo "   - S'inscrire avec 5 noms différents:"
echo "     • Joueur1"
echo "     • Joueur2" 
echo "     • Joueur3"
echo "     • Joueur4"
echo "     • Joueur5"

echo ""
echo "3️⃣ Vérifications à faire:"
echo "   - ✅ Tous les joueurs apparaissent dans la liste d'attente"
echo "   - ✅ Quand 5 joueurs sont connectés, redirection automatique"
echo "   - ✅ Dans gamepuzzle, le chat affiche 5 joueurs connectés"
echo "   - ✅ Tous les joueurs peuvent envoyer des messages"
echo "   - ✅ Tous les joueurs reçoivent les messages des autres"

echo ""
echo "4️⃣ Logs à surveiller dans la console:"
echo "   Backend:"
echo "   - '🚀 Mission démarrée pour la session DEFAULT avec 5 joueurs'"
echo "   - 'INFO: WebSocket /ws/chat/DEFAULT?pseudo=... [accepted]'"
echo ""
echo "   Frontend:"
echo "   - '👥 Joueurs connectés dans gamepuzzle: [...]'"
echo "   - '😊 Émojis des joueurs dans gamepuzzle: {...}'"
echo "   - 'WebSocket connecté !'"
echo "   - 'Message reçu dans gamepuzzle: {...}'"

echo ""
echo "5️⃣ Dépannage:"
echo "   - Si erreur 404: La session DEFAULT n'existe pas → redémarrer le serveur"
echo "   - Si erreur 403 WebSocket: Le joueur n'est pas dans la session → vérifier l'inscription"
echo "   - Si 0 joueurs dans le chat: Vérifier l'endpoint /sessions/DEFAULT/players"
echo "   - Si seul 1 joueur peut écrire: Vérifier la connexion WebSocket"

echo ""
echo "6️⃣ Test de connectivité:"
echo "   - Backend: http://localhost:8000/config"
echo "   - Session: http://localhost:8000/sessions/DEFAULT/players?pseudo=test"
echo "   - Émojis: http://localhost:8000/players/emojis"

echo ""
echo "✅ Instructions de test terminées !"
echo ""
echo "🎯 Prochaines étapes:"
echo "   1. Démarrer le frontend"
echo "   2. Tester avec 5 joueurs"
echo "   3. Vérifier que le chat fonctionne pour tous"
echo "   4. Signaler tout problème observé"